### ISSUE TITLE
Reforge wiki site down

### ISSUE THREAD

**Issue by puf-puf** [BohemiaInteractive/Arma-Reforger-Samples#2]
Yep, i know about, non themed message.

But https://wiki.reforger.armaplatform.com/ - down

https://feedback.reforger.armaplatform.com/ - same trouble

**Comment by tom4897** [comment]
Hello, thanks for the report. We're aware of the issue and will fix it soon. Meanwhile, the wiki can be accessed [here](https://feedback.bistudio.com/project/view/66/), and the feedback tracker [here](https://feedback.bistudio.com/project/view/66/).

**Comment by throwaway193** [comment]
> Hello, thanks for the report. We're aware of the issue and will fix it soon. Meanwhile, the wiki can be accessed [here](https://feedback.bistudio.com/project/view/66/), and the feedback tracker [here](https://feedback.bistudio.com/project/view/66/).

Seems like you sent the same link twice, was that intentional or is there a way to reach the wiki through the feedback tracker?

**Comment by BenRauzi** [comment]
@tom4897  You seem to have sent the same link twice.

**Comment by tom4897** [comment]
Sorry about that, this wasn't intentional. The documentation is available here: https://community.bistudio.com/wiki/Category:Arma_Reforger (scroll down to see the categories).

The documentation is a work-in-progress; more will come over time.
