### ISSUE TITLE
Google's protobufs support?

### ISSUE THREAD

**Issue by misnaged** [BohemiaInteractive/Arma-Reforger-Samples#3]
Is there any chances that protobuf support would be added? =)

**Comment by BohemiaIsTrash** [comment]
@misnaged  Death to google. Death to "univeristies" [dumpsterveristies]. Death to the garbage and useless so called "health" "sector" and every moron who promotes that trash. Death to prefixes when mentioning first names.

Mechanical Engineering is the great subject.
