### ISSUE TITLE
There is an error in the Samples of faces and their UVmaps.

### ISSUE THREAD

**Issue by jovechiere** [BohemiaInteractive/Arma-Reforger-Samples#4]
There are three different heads with different UVmaps.

1 is present in _Character_Rigify_Example.blend_ 
2 is present in _Head_Template.fbx_ that belongs to _Assets/Characters/Basebody/Basebody/Basebody_Male_Head_01.xob_

3 the faces that appear in ArmA Reforger are not any of the two previous ones...
They are the _Assets/Characters/Heads/Head_White_02/Data/Head_White_02_BCR.edds_ (for example) that belong to _Assets/Characters/Heads/Heads/Head_White_02/Head_White_02.xob_

Where can I get this face in .FBX to be able to work correctly in ArmA Reforger faces and textures?

Example images: https://imgur.com/a/X7JHRgW

**Comment by reyhard** [comment]
Unfortunately it is rather unlikely to get other heads for retexturing but perhaps in future, it might be possible to change UV mapping of Head_Template.fbx to match  Head_xx_xx variants.

**Comment by lucasfuoco** [comment]
The head doesn't seem to snap correctly to the base body in the Reforger tools. When playing, the head floats on top of the body not reacting to the body's armature. Any solutions?
